FROM node:{{nodeVersion}}

MAINTAINER Tomasz Netczuk

RUN npm i -g yarn@{{yarnVersion}}
RUN npm cache clean
# fix for: .roadrunner.json error https://github.com/yarnpkg/yarn/issues/1724
RUN mkdir -p /root/.cache/yarn/
RUN yarn --version
